export const PRODUCTS_SEED = [
  {
    name: 'Diffuser Air 2 Discovery Kit',
    price: 74.74,
    originalPrice: 213.59,
    category: 'Diffusers',
    image: 'https://placehold.co/600x400?text=Diffuser+Air+2+Discovery+Kit',
    description: 'Covers up to 1,000 sq ft. Includes Top 3 Hotel Scents',
    rating: 5,
    reviews: 455,
    badge: 'SALE',
    saveAmount: 138,
    customButtonText: 'Customize your Discovery Kit',
    flashSale: { code: 'STORM', endTime: new Date(Date.now() + 8 * 3600 * 1000).toISOString() },
  },
  {
    name: 'Diffuser Air 2',
    price: 59.99,
    originalPrice: 200.0,
    category: 'Diffusers',
    image: 'https://placehold.co/600x400?text=Diffuser+Air+2',
    description: 'Covers up to 1,000 sqft. Pairs 120 mL Fragrance Oil',
    rating: 5,
    reviews: 320,
    badge: 'SALE',
    saveAmount: 140,
    variants: ['Black', 'Silver', 'White', 'Graphite Gold'],
    customButtonText: 'Add to Cart',
    flashSale: { code: 'STORM', endTime: new Date(Date.now() + 8 * 3600 * 1000).toISOString() },
  },
  {
    name: 'Diffuser Mini 2 LE Discovery Kit',
    price: 64.06,
    originalPrice: 119.61,
    category: 'Diffusers',
    image: 'https://placehold.co/600x400?text=Diffuser+Mini+2+LE+Discovery+Kit',
    description: 'Covers 500 sqft. Includes Top 3 Hotel Scents',
    rating: 5,
    reviews: 206,
    badge: 'SALE',
    saveAmount: 55,
    variants: ['Black', 'Silver', 'White', 'Red', 'Space Gray', 'Graphite Gold'],
    customButtonText: 'Customize your Discovery Kit',
    flashSale: { code: 'STORM', endTime: new Date(Date.now() + 8 * 3600 * 1000).toISOString() },
  },
  {
    name: 'Diffuser Mini 2 LE',
    price: 29.99,
    originalPrice: 100.0,
    category: 'Diffusers',
    image: 'https://placehold.co/600x400?text=Diffuser+Mini+2+LE',
    description: 'Up to 500 sqft coverage. Pairs 20 mL Fragrance Oil',
    rating: 4.9,
    reviews: 150,
    badge: 'SALE',
    saveAmount: 70,
    variants: ['Black', 'Silver', 'White', 'Red', 'Space Gray', 'Graphite Gold'],
    customButtonText: 'Add to Cart',
    flashSale: { code: 'STORM', endTime: new Date(Date.now() + 8 * 3600 * 1000).toISOString() },
  },
  {
    name: 'Diffuser Pro 2',
    price: 80.09,
    originalPrice: 512.65,
    category: 'Diffusers',
    image: 'https://placehold.co/600x400?text=Diffuser+Pro+2',
    description: 'Covers up to 2,000 sqft. Large Spaces',
    rating: 5,
    reviews: 100,
    badge: 'SALE',
    saveAmount: 432.52,
    customButtonText: 'Customize your Discovery Kit',
    flashSale: { code: 'STORM', endTime: new Date(Date.now() + 8 * 3600 * 1000).toISOString() },
  },
  {
    name: 'Diffuser HVAC 2',
    price: 199.99,
    originalPrice: 800.0,
    category: 'Diffusers',
    image: 'https://placehold.co/600x400?text=Diffuser+HVAC+2',
    description: 'Covers up to 5,000 sqft. 500 ML Bottle Included',
    rating: 5,
    reviews: 85,
    badge: 'SALE',
    saveAmount: 600,
    customButtonText: 'Add to Cart',
    flashSale: { code: 'STORM', endTime: new Date(Date.now() + 8 * 3600 * 1000).toISOString() },
  },
];
