import type { ComponentType } from 'react';
import {
  HiCollection,
  HiSparkles,
  HiTag,
  HiGlobe,
  HiCloud,
  HiFire,
  HiBeaker,
  HiTruck,
  HiStar,
  HiShieldCheck,
  HiHeart,
  HiCog,
  HiGift,
  HiHome,
  HiOfficeBuilding,
  HiUsers,
  HiClock,
  HiLockClosed,
  HiArrowRight,
  HiBell,
  HiChat,
  HiUser,
  HiShoppingBag,
  HiPlus,
  HiChartBar,
  HiCube,
  HiShoppingCart,
  HiLogout,
  HiTrendingUp,
  HiTrendingDown,
  HiArrowLeft,
  HiSearch,
  HiCheck,
  HiX,
  HiCurrencyDollar,
  HiEye,
  HiCalendar,
  HiLocationMarker,
  HiChevronDown,
  HiMinus,
  HiPencil,
  HiTrash,
  HiExclamationCircle,
  HiArrowUp,
  HiArrowDown,
} from 'react-icons/hi';
import { GiPerfumeBottle, GiSpray, GiTrophy, GiRabbit, GiWindSlap } from 'react-icons/gi';
import { FaBaby } from 'react-icons/fa';

export type IconComponent = ComponentType<{ className?: string }>;

const ICON_REGISTRY: Record<string, IconComponent> = {
  // Header icons
  HiCollection,
  HiSparkles,
  HiTag,
  HiGlobe,
  HiCloud,
  HiFire,
  HiBeaker,
  GiPerfumeBottle,
  GiSpray,
  // Home section icons
  GiTrophy,
  HiTruck,
  HiStar,
  HiShieldCheck,
  HiHeart,
  HiCog,
  HiGift,
  HiHome,
  HiOfficeBuilding,
  HiUsers,
  HiClock,
  HiLockClosed,
  HiArrowRight,
  GiRabbit,
  GiWindSlap,
  FaBaby,
  // Seller page icons
  HiBell,
  HiChat,
  HiUser,
  HiShoppingBag,
  HiPlus,
  HiChartBar,
  HiCube,
  HiShoppingCart,
  HiLogout,
  HiTrendingUp,
  HiTrendingDown,
  HiArrowLeft,
  HiSearch,
  HiCheck,
  HiX,
  HiCurrencyDollar,
  HiEye,
  HiCalendar,
  HiLocationMarker,
  HiChevronDown,
  HiMinus,
  HiPencil,
  HiTrash,
  HiExclamationCircle,
  HiArrowUp,
  HiArrowDown,
  // Lowercase aliases for backward compatibility
  collection: HiCollection,
  sparkles: HiSparkles,
  tag: HiTag,
  globe: HiGlobe,
  cloud: HiCloud,
  fire: HiFire,
  beaker: HiBeaker,
  perfume: GiPerfumeBottle,
  spray: GiSpray,
};

export function getIconById(id: string): IconComponent {
  return ICON_REGISTRY[id] ?? HiCollection;
}

